"""Tables D1, D2 and D3 for the Data chapter, built from source. No number is typed here.

Every figure in the three tables is read from a measured artefact at build time:

  data_chapter_measurements.json  coverage states, per-build split boundaries and episode
                                  counts, regime mix, depth by hour
                                  (reports/diagnostics/data_chapter_measure.py)
  phase1_qa.json                  the pipeline stages and their integrity gates
  tick_class_measurement.json     tick, relative tick and the spread distribution
  adv/btc_adv.json                the recorded-book average daily volume and its skew
  trade_volume_202512.json        the per-order month's traded volume
                                  (reports/diagnostics/l4_trade_volume.py)

ONE EXCEPTION, DECLARED. Table D3's Panel B lists the simulator's episode-seed blocks with
their governance status (development, reserve, sealed, spent). A block's STATUS is a human
designation recorded in the partition audit, addendum (Z) of qrm_step5_remediation.md; it is
not derivable from any file, because "sealed and spent" is a statement about how a partition
was licensed and used, not about its contents. Those cells are therefore literals carried
from (Z), marked below, and every numeric cell in the same table is not.

Output: reports/tables/d1_sources.tex, d2_pipeline.tex, d3_partitions.tex
"""
from __future__ import annotations

import json
from pathlib import Path

S = Path("/Users/fardeenidrus/Desktop/MSc Dissertation/scratch_hyperliquid")
HERE = Path(__file__).resolve().parent
REPORTS = HERE.parent

M = json.loads((S / "oxford_l4" / "data_chapter_measurements.json").read_text())
QA = json.loads((REPORTS / "phase1_qa.json").read_text())
TC = json.loads((S / "oxford_l4" / "tick_class" / "tick_class_measurement.json").read_text())
ADV = json.loads((S / "adv" / "btc_adv.json").read_text())
TVALL = json.loads((S / "oxford_l4" / "trade_volume_202512.json").read_text())
TV = TVALL["december_only"]

RC = M["raw_coverage"]
B = M["builds"]


def esc(s: str) -> str:
    return s.replace("%", r"\%").replace("&", r"\&").replace("_", r"\_")


def n(x: float, dp: int = 0) -> str:
    """Thousands-separated fixed-point, so a table never invents precision."""
    return f"{x:,.{dp}f}"


# ---------------------------------------------------------------- D1: sources and roles

def table_d1() -> str:
    spread = TC["spread"]["full_month"]
    seven = TC["spread"]["first_7_day_sample"]
    grid_rows_full = 24 * 60 * 60 * 2  # a 0.5-second grid over a full UTC day
    n_l4_days = spread["n_days"]
    prim = 25.0  # the simulator's primary order, BTC

    rows = [
        (r"Book snapshots (Level 2)",
         r"the price and the volume standing at each level, both sides, at the instant the snapshot was taken",
         r"20 price levels each side, averaged into 1-minute and 10-second bars",
         f"{RC['span_start']} to {RC['span_end']} ({RC['span_days']} days)",
         f"{n(RC['n_raw_files'])} separate hourly files",
         r"replaying the historical book"),
        (r"Book changes, order by order (Level 4)",
         r"one change to the visible book, giving the order's identifier, side, price and new size. It has no timestamp",
         f"the book rebuilt at 20 price levels each side, once every half second; 85 columns, so {n(grid_rows_full)} rows in a full day",
         f"December 2025, {n_l4_days} of {n_l4_days} days",
         f"{n(spread['n_samples'])} half-second book snapshots",
         r"fitting the simulator; measuring the venue's order flow"),
        (r"Order events with timestamps (Level 4)",
         r"one record per order event, with a timestamp accurate to the nanosecond and the order's identifier",
         r"not turned into a book; used to timestamp the book changes, matched by order identifier",
         r"December 2025",
         r"---",
         r"supplying the timestamps the book changes lack"),
        # The trade stream was collected and every volume figure in this chapter comes from it,
        # but it had no row here until 2026-08-09, so a reader met three sources and four
        # numbers. The book changes say what was STANDING; the trades say what was BOUGHT.
        (r"Trades (the venue's own print)",
         r"one transaction that actually took place, with its price, size and time",
         r"not turned into a book. The book changes say what was standing in the queues; the trades say what changed hands",
         f"December 2025, {TV['n_dates']} of {TV['n_dates']} days",
         # TV, not TVALL: TVALL['n_btc_trades'] counts all 33 archive dates, 2025-11-30 to
         # 2026-01-01, while the period cell beside it says December. The spill is 27,495
         # trades, 0.230%. december_only gained its own count on 2026-08-10 (audit T1).
         f"{n(TV['n_btc_trades'])} BTC trades",
         r"every traded-volume figure in this chapter"),
    ]

    out = [r"% Auto-generated by reports/tables/make_data_tables.py. Do not edit.",
           r"\newcolumntype{R}[1]{>{\raggedright\arraybackslash}p{#1}}",
           r"\begin{tabular}{@{}R{2.2cm} R{3.0cm} R{3.1cm} R{2.0cm} R{2.0cm} R{1.9cm}@{}}",
           r"\toprule",
           r"what was collected & one record holds & processed into & period covered & how much data & used for \\",
           r"\midrule"]
    # Each source row runs to four or five lines, so without separation the three run
    # together. A light rule stays inside booktabs convention; vertical rules do not.
    for i, r in enumerate(rows):
        out.append(" & ".join(esc(c) for c in r) + r" \\")
        if i < len(rows) - 1:
            out.append(r"\addlinespace[2pt]\cmidrule(lr){1-6}\addlinespace[2pt]")
    out += [r"\midrule",
            r"\multicolumn{6}{@{}l}{\emph{Instrument, measured across all "
            + f"{n_l4_days} days and {n(spread['n_samples'])} half-second samples}}" + r"} \\",
            r"\midrule"]

    inst = [
        ("tick size", r"\$1.00, constant across all " + f"{n_l4_days} days"),
        ("median mid", r"\$" + n(spread["median_mid"], 2)),
        # Typeset as the prose does. ":.3e" printed "1.131e-05", a machine literal in the one
        # table a marker opens to check the prose's $1.13\times10^{-5}$ against.
        ("relative tick", f"${spread['relative_tick'] * 1e5:.2f}" + r"\times10^{-5}$"),
        (r"P(spread $=$ 1 tick)", f"{100 * spread['p_spread_1_tick']:.1f}\\% "
                                  f"(first 7-day sample: {100 * seven['p_spread_1_tick']:.1f}\\%)"),
        ("mean spread", f"{spread['mean_spread_ticks']:.3f} ticks, "
                        f"{spread['mean_spread_bps']:.4f} bps"),
    ]
    for k, v in inst:
        out.append(f"\\multicolumn{{2}}{{@{{}}p{{5.5cm}}}}{{{k}}} & "
                   f"\\multicolumn{{4}}{{p{{9.7cm}}@{{}}}}{{{v}}} \\\\")

    out += [r"\midrule",
            r"\multicolumn{6}{@{}l}{\emph{How much the venue trades, and what an order is a "
            r"share of it}} \\",
            r"\midrule"]

    vol = [
        ("average daily volume, two-year span",
         f"{n(ADV['adv_btc'], 2)} BTC a day "
         f"({ADV['window']['start']} to {ADV['window']['end']})"),
        ("median daily volume, same span",
         f"{n(ADV['median_daily_btc'], 0)} BTC, with a range of {n(ADV['min_daily_btc'], 0)} "
         f"to {n(ADV['max_daily_btc'], 0)}"),
        ("average daily volume, December 2025",
         f"{n(TV['mean_daily_btc'], 0)} BTC a day ({TV['date_first']} to {TV['date_last']})"),
        ("order sizes used with the historical snapshots",
         ", ".join(f"{ADV['adv_btc'] * p / 100:.2f} BTC" for p in (0.5, 1.0, 2.0))
         + " (0.5\\%, 1\\% and 2\\% of the two-year daily average)"),
        ("order size used in the simulator",
         f"{prim:g} BTC, which is {100 * prim / TV['mean_daily_btc']:.3f}\\% of an average "
         f"December day"),
    ]
    for k, v in vol:
        out.append(f"\\multicolumn{{2}}{{@{{}}p{{5.5cm}}}}{{{k}}} & "
                   f"\\multicolumn{{4}}{{p{{9.7cm}}@{{}}}}{{{v}}} \\\\")

    out += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(out) + "\n"


# ------------------------------------------- D1b: the instrument, as symbol / quantity / value

def table_d1b_instrument() -> str:
    """Table 3.1: the instrument's measured properties, one symbol per quantity.

    REBUILT 2026-08-13 on Carlo's comment: "this can stay as a table if you just introduce some
    mathematical notation (which you need later anyways) for volume, order sizes etc and turn it
    into a simple variable - value table." Six columns of phrases became three of symbol,
    quantity and value.

    THREE THINGS LEFT, each for a stated reason.
      * Both order-size rows. They are experimental design, not properties of the instrument,
        no prose in chapter 3 uses the ladder, and `m2_tracks.tex` already carries it with the
        environment and cadence that make it readable. Methodology owns Q.
      * "(first 7-day sample: 94.3%)". A measurement taken before the month was processed is an
        intermediate step of development, which his general comment rules out.
      * The caption's volume sentence, which restated rows of the table beneath it.

    ONE THING ARRIVED. December's median daily volume, 30,754 BTC, which was reachable only
    through the caption. The mean and the median are needed on BOTH periods because the study
    expresses order sizes as a percentage of daily volume against two different denominators;
    printing either as "%ADV" without saying which average is a factual error. The subscripts
    exist for that reason and are not decoration.

    THE MID IS A MEDIAN OF MEDIANS. `tick_class_measure.py:188-189` takes np.median over the 31
    per-day medians, not over the 5,355,301 observations, and the relative tick follows from it
    ($1.00 / 88,417.50 reproduces the reported figure exactly). The old panel header said
    "measured across all 31 days and 5,355,301 half-second samples", which implied pooled. The
    note below says what was actually computed.

    NO NUMBER IS TYPED. The tick was the one exception in the old table (a literal "\\$1.00" at
    what was line 112); it now reads `tick_values_seen`, which the measurement asserts is a
    single value across all 31 days.
    """
    sp = TC["spread"]["full_month"]
    ticks_seen = TC["tick_values_seen"]
    assert TC["tick_constant_across_days"] and len(ticks_seen) == 1, ticks_seen
    tick = float(ticks_seen[0])

    panel_a = [
        (r"$\delta$", "tick size", rf"\${tick:,.2f}"),
        (r"$\tilde{p}$", "median mid-quote", r"\$" + n(sp["median_mid"], 2)),
        # Typeset as the prose does. ":.3e" printed "1.131e-05", a machine literal in the one
        # table a marker opens to check the prose's $1.13\times10^{-5}$ against.
        (r"$\delta/\tilde{p}$", "relative tick",
         f"${sp['relative_tick'] * 1e5:.2f}" + r"\times10^{-5}$"),
        (r"$\bar{s}$", "mean spread",
         f"{sp['mean_spread_ticks']:.3f} ticks, {sp['mean_spread_bps']:.4f} bps"),
        (r"$P(s=\delta)$", "probability the spread is one tick",
         f"{100 * sp['p_spread_1_tick']:.1f}\\%"),
    ]
    panel_b = [
        (r"$\bar{V}_{2\mathrm{y}}$",
         f"average daily volume, {ADV['window']['start']} to {ADV['window']['end']}",
         f"{n(ADV['adv_btc'], 0)} BTC"),
        (r"$\tilde{V}_{2\mathrm{y}}$", "median daily volume, same span",
         f"{n(ADV['median_daily_btc'], 0)} BTC, range {n(ADV['min_daily_btc'], 0)} to "
         f"{n(ADV['max_daily_btc'], 0)}"),
        (r"$\bar{V}_{\mathrm{Dec}}$", "average daily volume, December 2025",
         f"{n(TV['mean_daily_btc'], 0)} BTC"),
        (r"$\tilde{V}_{\mathrm{Dec}}$", "median daily volume, December 2025",
         f"{n(TV['median_daily_btc'], 0)} BTC"),
    ]

    # 0.90, not 0.94: the two internal column boundaries cost 4\tabcolsep, and the note is set
    # to the same total so it cannot run past the rules above it. Same arithmetic as
    # make_methodology_appendix_tables.py.
    note = r"\multicolumn{3}{@{}p{\dimexpr0.90\linewidth+4\tabcolsep}@{}}"
    L = [r"% Auto-generated by reports/tables/make_data_tables.py. Do not edit.",
         r"\begin{tabular}{@{}p{0.10\linewidth}p{0.45\linewidth}p{0.35\linewidth}@{}}",
         r"\toprule",
         r"\multicolumn{3}{@{}l}{\emph{Panel A. Price and spread, December 2025}} \\",
         r"\midrule"]
    for s, q, v in panel_a:
        L.append(f"{s} & {q} & {v} \\\\")
    L += [note + r"{\footnotesize Measured on the reconstructed half-second book, "
          + n(sp["n_samples"]) + r" observations. The mid-quote is the median across the "
          + f"month's {sp['n_days']} daily medians, and the relative tick follows from it."
          + r"} \\",
          r"\addlinespace[0.6em]", r"\midrule",
          r"\multicolumn{3}{@{}l}{\emph{Panel B. Traded volume}} \\",
          r"\midrule"]
    for s, q, v in panel_b:
        L.append(f"{s} & {q} & {v} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


# --------------------------------------------------------- D2: pipeline and integrity

def table_d2() -> str:
    s0, s1 = QA["stage0_source_coverage"], QA["stage1_pull"]
    s3, s4 = QA["stage3_minute"], QA["stage4_features"]
    s5, s6 = QA["stage5_regimes"], QA["stage6_datasets"]
    p = s4["params"]
    dropped = s4["feature_valid_rows"] - s6["rows"]

    thr_1min = M["volatility"]["dataset"]["threshold"]
    rows = [
        ("downloading the raw files",
         f"{n(s0['hours_present'])} hourly files, one for each hour obtained. "
         f"{s0['days_fully_covered']} days arrived with all 24 hours, "
         f"{len(s0['days_partial'])} with only some, "
         f"{len(s0['days_missing'])} with none although they were requested, and "
         f"{s0['days_skipped']} were never requested because the venue's archive holds nothing "
         f"for those weeks",
         f"{n(s0['hours_present'])} of the {n(s0['hours_expected'])} hours in the "
         f"{s0['days_in_range_excluding_skips']} days requested, or {s0['coverage_pct']}\\%. "
         f"Measured instead against all {RC['span_days']} days of the two years, including the "
         f"{s0['days_skipped']} never requested, it is {RC['coverage_pct_calendar']}\\%"),
        ("checking the download",
         f"{n(s1['raw_files'])} files on disk against {n(s1['expected'])} expected",
         "every file matched byte for byte" if s1["byte_exact"] else "MISMATCH"),
        ("building one book per minute",
         f"{n(s3['minutes_present'])} minutes, no duplicates, a median of "
         f"{s3['median_snapshots_per_min']:g} snapshots behind each minute",
         "timestamps strictly increasing; bid prices below ask prices at every level"),
        ("computing the input variables",
         f"{n(s4['feature_valid_rows'])} minutes usable of {n(s4['rows'])} ({s4['valid_pct']}\\%). "
         f"Five variables describe each minute: the average gap between the best buy and best "
         f"sell price; the imbalance between the buy and sell volume resting on the best "
         f"{p['imbalance_depth']} levels; the sell-side volume resting on those levels; the "
         f"price change over the previous {p['return_lookback']} minutes; and price volatility "
         f"over the previous {p['vol_window']} minutes",
         "a minute is usable only if all five variables can be computed for it"),
        ("the volatility window, and its cost",
         f"volatility is computed from the previous {p['vol_window']} minutes, and the price "
         f"change from the previous {p['return_lookback']}. If any minute inside either stretch "
         f"is absent, the variable cannot be computed and the minute is discarded rather than "
         f"estimated by interpolation",
         f"no {p['vol_window']}-minute window is ever completed across absent minutes; "
         "\\Cref{fig:d1-coverage} shows where the loss falls"),
        ("cutting the data into episodes",
         f"{n(s4['feature_valid_rows'])} usable minutes became {n(s6['rows'])}. The "
         f"{n(dropped)} difference is minutes left over at the ends, too few to complete an "
         f"episode",
         f"{n(s6['rows'])} $\\div$ {s6['rows'] // s6['episodes']} steps $=$ "
         f"{n(s6['episodes'])} episodes exactly"),
        ("labelling each episode calm or volatile",
         # NOT "the training episodes". The median is taken over the whole training file,
         # before validation is carved out of it (train.py:60), so it covers training AND
         # validation. Table D3 defines training episodes as the 22,016 the agent learns
         # on, which is the conventional usage, so the two would name different sets.
         f"the dividing line is {thr_1min:.6f}, the median volatility of every episode "
         f"before the test period, so half of those fall on each side",
         f"{n(s5['n_episodes'])} episodes labelled"),
        ("splitting into training and test",
         f"{n(s6['train_rows'])} training rows and {n(s6['test_rows'])} test rows, split by "
         f"date",
         "every training row is dated before every test row"),
        ("guarding against leakage",
         f"every variable is computed from completed minutes only and then shifted by one "
         f"minute, so the values available at any decision point come from minutes strictly "
         f"before it. {s6['nan_in_core_fields']} missing values in the core fields, and the "
         f"scaling constants are computed on the training portion alone and applied unchanged "
         f"elsewhere",
         "no test-period information enters training; the one-minute shift is enforced in code "
         "and unit-tested"),
        ("reproducibility",
         "the pipeline draws no random numbers at any stage",
         "the same input and settings reproduce every file exactly"),
    ]

    out = [r"% Auto-generated by reports/tables/make_data_tables.py. Do not edit.",
           r"\begin{tabular}{@{}p{2.7cm} p{7.2cm} p{5.3cm}@{}}",
           r"\toprule",
           r"step & what it produced & what was checked \\",
           r"\midrule"]
    for a, b, c in rows:
        out.append(f"{esc(a)} & {b} & {c} \\\\")
    out += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(out) + "\n"


# -------------------------------------------------------- D3: partitions and governance

# Panel B literals. Source: qrm_step5_remediation.md addendum (Z), the two-pass partition
# audit. Status is a licensing designation and has no machine-readable source; see the module
# docstring. Numbers inside this panel are counts recorded by that audit.
#
# WIDTH. The two right-hand columns were shortened 2026-08-06: the panel measured 21.0cm
# against a 16.0cm text width and lost the right of "standing now" off the page. "used up"
# became "spent", the repeated "no advantage found" became "no advantage", and the clause
# "no result was ever judged on them" moved into the description, where the same statement
# already appears for 1e6. No designation changed.
PANEL_B = [
    ("1e6", "development", "watching training progress. No result was ever judged on it",
     "many", "still available"),
    ("5e6", "development", "the working set: tuning, screening and everyday comparisons",
     "27 campaigns", "still available"),
    ("18e6", "development", "the working set for the environment with the injected signal",
     "4 campaigns", "still available"),
    ("6e6", "reserve", "held back to check whether a development result repeated",
     "1 comparison", "spent"),
    # 19e6 and 21e6 are extension-reserved blocks (qrm_step4_criteria.md:1020-1021; §8
    # Amendment A2 at :1076). Both belong to the injected-signal simulator; neither row said so.
    ("19e6", "reserve", "injected-signal reserve; the designation expired unused, then was "
     "spent on the pacing-drift test", "1", "spent"),
    ("9e6", "confirmation", "first confirmation of the main comparison, one attempt only",
     "1", "spent"),
    ("13e6", "confirmation", "second confirmation of the main comparison, one attempt only",
     "1", "spent"),
    ("25e6", "confirmation", "created for the amended observation specification",
     "1, two arms", "spent"),
    ("17e6", "confirmation", "created for the injected-signal extension, one attempt only",
     "1", "spent"),
    ("21e6", "confirmation", "created to confirm the best attainable improvement with the "
     "injected signal, one attempt", "1", "spent"),
    ("3e6", "environment check", "certifying the simulator itself, never used to judge a method",
     "---", "not a comparison set"),
    # CORRECTED 2026-08-06. This row read "30e6, 31e6, 77M" and omitted seven ranges that the
    # partition audit (Z) declares at qrm_step5_remediation.md:2904-2909 -- 30.0/30.1/30.2M and
    # 30.3/30.4/30.5/30.55M. In a table whose job is to say which seed sets exist, an omission
    # is worse than a clumsy phrase. 30e6 IS 30.0M: it appears twice in (Z) because it was used
    # for diagnostics and later for the power-analysis measurement, which is why neither it nor
    # 31e6 may ever be called a fresh block.
    ("30.0--30.55M, 31e6, 77M", "measurement",
     "diagnostic measurements only. No result was ever judged on them",
     "---", "not a comparison set"),
]

# Panel A's rows. The panel used to run one row per version across seven columns and measured
# 21.7cm against a 16.0cm text width, losing its regime-mix column off the page. Turning it
# ninety degrees fits the page and reads better: the headline version is a column the eye runs
# down. The timestamp pair became two rows for the same reason.
PANEL_A_ROWS = [
    ("bar width", lambda b, k: {"dataset": "1 minute", "dataset_10s": "10 seconds",
                                "dataset_10s_10min": "10 seconds"}[k]),
    ("decisions per episode", lambda b, k: n(b["steps_per_episode"])),
    ("episode length", lambda b, k: {"dataset": "30 minutes", "dataset_10s": "30 minutes",
                                     "dataset_10s_10min": "10 minutes"}[k]),
    ("training episodes", lambda b, k: n(b["episodes_train_only"])),
    # "validation", not "tuning": the Results chapter's exhibits and prose already use
    # validation for these same episodes, and one partition must not carry two names
    # across chapters. Decided 2026-08-06. Line 236's "tuning" is an ACTIVITY a seed set
    # was used for, not this partition's name, and stays.
    ("validation episodes", lambda b, k: n(b["episodes_validation"])),
    ("held-out test episodes", lambda b, k: n(b["episodes_test"])),
    ("last training bar", lambda b, k: r"\scriptsize " + b["train_last_ts"][:19]),
    ("first test bar", lambda b, k: r"\scriptsize " + b["test_first_ts"][:19]),
    ("test episodes: calm / volatile",
     lambda b, k: f"{n(b['test_regime']['calm'])} / {n(b['test_regime']['volatile'])}"),
]

# "(main)" was removed 2026-08-06: it read as "the study's main track", which is the reactive
# simulator, not this dataset. Which version the chapter's quoted figures come from is stated in
# the panel note below instead.
BUILD_ORDER = [("dataset_10s", r"\textbf{10-second}"),
               ("dataset", "1-minute"),
               ("dataset_10s_10min", "10-second, shorter episode")]


def table_d3() -> str:
    out = [r"% Auto-generated by reports/tables/make_data_tables.py. Do not edit.",
           r"\begin{tabular}{@{}l r r r@{}}",
           r"\toprule",
           " & " + " & ".join(label for _, label in BUILD_ORDER) + r" \\",
           r"\midrule"]
    for label, cell in PANEL_A_ROWS:
        out.append(f"{label} & " + " & ".join(cell(B[key], key) for key, _ in BUILD_ORDER)
                   + r" \\")
    out += [r"\midrule",
            # The note NAMES the design fractions and EXPLAINS the boundary gap. Both were
            # implicit before: "the same fraction" left the fraction unnamed, and the two
            # timestamp rows showed a gap that reads as missing data unless the buffer is said.
            # The order of the two carves was not stated, so a reader could not tell which was
            # taken first. It is test first, then validation out of what is left, which is what
            # puts validation directly against the test boundary.
            r"\multicolumn{4}{@{}p{12.4cm}}{\footnotesize The last "
            f"{B['dataset_10s']['test_fraction_pct']:.0f}\\% of each version's episodes are held "
            r"out as the test set; validation is then the last 15\% of what remains, so the "
            r"three run train, validation, test in time order. "
            r"The rule is identical across the three; "
            r"because they hold different numbers of episodes, the same fraction falls on a "
            r"different date in each. Between the last training bar and the first test bar sits "
            f"{B['dataset_10s']['boundary_buffer_episodes']:.0f} whole episode plus one bar, so "
            # "Both fractions were fixed before any training" asserted a chronology no artefact
            # dates. The structural claim is verifiable and stronger: the split is baked into
            # the dataset files the agents read.
            r"no episode straddles the split. The split is written into the dataset files the "
            r"agents read, so no training could have preceded it. "
            r"\textbf{Episode counts quoted elsewhere in this "
            r"chapter are the 10-second version's.}} \\",
            r"\bottomrule",
            r"\end{tabular}",
            r"",
            r"\vspace{0.6em}",
            r"",
            # Ragged right, set inline rather than through \newcolumntype: d1_sources.tex
            # already defines R, and \newcolumntype errors on a second definition if both
            # tables are input into the same document.
            r"\begin{tabular}{@{}>{\raggedright\arraybackslash}p{1.5cm} l >{\raggedright\arraybackslash}p{4.9cm} l l@{}}",
            r"\toprule",
            r"seed set & kind & what it was for & times used & standing now \\",
            r"\midrule"]
    # Twelve rows, most of them wrapping to two or three lines. A rule under every row would be
    # heavy and against booktabs practice; a rule under every KIND separates the five governance
    # groups, which is the structure a reader is actually navigating by.
    prev_kind = None
    for blk, kind, role, uses, status in PANEL_B:
        if prev_kind is not None and kind != prev_kind:
            out.append(r"\addlinespace[2pt]\cmidrule(lr){1-5}\addlinespace[2pt]")
        prev_kind = kind
        out.append(f"{esc(blk)} & {esc(kind)} & {esc(role)} & {esc(uses)} & {esc(status)} \\\\")
    out += [r"\midrule",
            # The opening sentence used to define a confirmation set. Section 3.4's third
            # paragraph now does that, so the note keeps only the integrity claim, which no
            # prose carries, and spends the room on the term the table uses twice and nothing
            # explained: the second version of the simulator.
            r"\multicolumn{5}{@{}p{13.6cm}}{\footnotesize None of the five confirmation sets "
            r"appears in more than one result. Two simulators are in use: the "
            r"one fitted to the December records, and a second into which a signal whose "
            r"strength was measured from those same records has been injected. The Methodology "
            r"chapter describes both, and a set belongs to the fitted simulator unless its row says "
            r"otherwise.} \\",
            r"\bottomrule",
            r"\end{tabular}",
            r"",
            r"\vspace{0.6em}",
            r"",
            *panel_c()]
    return "\n".join(out) + "\n"


def panel_c() -> list[str]:
    """The December per-order month, split by hour. A THIRD kind of division.

    Every cell is measured; `december_partition` in the measurement script asserts the grid
    against the split report and the labelled hours against the month's calendar. The note
    must NOT say the month was cut at a date: the split is chronological within each regime,
    so nine dates supply hours to both sides.
    """
    D = M["december_partition"]
    F = D["fit_of_record"]
    c = D["cells"]
    cal = round(100 * D["calibrate_fraction"])
    u = D["unlabelled_hour"]
    # Panel C is a 2x2 contingency table, not a wide listing like Panels A and B. Its note is
    # set to the grid's own width rather than the 15.2cm those panels use: a wider note stretches
    # the four columns across the page and strands the total column at the right margin, which
    # is what the first build did.
    return [
        r"\begin{tabular}{@{}l r r r@{}}",
        r"\toprule",
        # "available to fit", not "used to fit". The split is not the consumption: the fit of
        # record drew 60 of the 557 calibrating hours. Corrected 2026-08-06 after the examiner.
        r" & available to fit the simulator & held back to test it & all hours \\",
        r"\midrule",
        f"calm hours & {n(c['calm/calibrate'])} & {n(c['calm/holdout'])} & "
        f"{n(D['calm_total'])} \\\\",
        f"volatile hours & {n(c['volatile/calibrate'])} & {n(c['volatile/holdout'])} & "
        f"{n(D['volatile_total'])} \\\\",
        r"\midrule",
        f"all hours & {n(D['calibrate_total'])} & {n(D['holdout_total'])} & "
        f"{n(D['hours_labelled'])} \\\\",
        r"\midrule",
        r"\multicolumn{4}{@{}p{11.6cm}}{\footnotesize An hour is volatile if the standard "
        # "the month's median" did not say median OF WHAT, ACROSS WHAT, and was read as the
        # median price change rather than the median across the month's hours. The line was
        # placed to halve the month; the calm and volatile medians are the RESULT of that
        # split, checked afterwards to see whether it separated anything, and now say so.
        f"deviation of its one-second price changes reaches "
        f"\\${D['threshold_vol_1s']:.2f}, the median across the month's "
        f"{n(D['hours_labelled'])} hours. Splitting there leaves a median calm hour of "
        f"\\${D['median_vol_calm']:.2f} against \\${D['median_vol_volatile']:.2f} for the "
        f"volatile ones. Within each group the "
        f"earliest {cal}\\% of hours are available and the latest {100 - cal}\\% held back, so no "
        f"held-back hour precedes a fitting hour of its own group. \\textbf{{The first column is "
        f"what the fit could draw on, not what it used}}: the simulator was built from "
        f"{F['n_blocks_per_regime']} runs of {F['block_len_hours']} consecutive hours in each "
        f"group, {F['hours_total']} hours in all. \\textbf{{The month is not cut at a date}}: "
        f"the groups interleave, so {D['n_dates_on_both_sides']} December dates supply hours to "
        f"both sides, though no hour supplies both. {n(D['hours_labelled'])} of the month's "
        f"{n(D['hours_expected'])} hours are labelled; the hour beginning midnight on 1 December "
        f"holds {u['minutes_present']:.0f} minutes of book data against the "
        f"{u['snapshots_required'] // 120} required, because recording starts twelve and a half "
        # Points at Table 3.4, which states the warm-up. Section 3.3's PROSE never mentions it.
        f"minutes into the month (\\Cref{{tab:d2b-perorder}})."
        r"} \\",
        r"\bottomrule",
        r"\end{tabular}",
    ]


def split_d1(body: str) -> dict:
    """D1's two halves, one file each.

    One table was doing two jobs: WHAT WAS COLLECTED (a row per stream) and WHAT THE INSTRUMENT
    IS LIKE (tick, spread, volumes, order sizes). It absorbed that for three source rows, at
    4.2pt over its float box. Adding the trade row on 2026-08-09 took the overflow to 98.9pt,
    about 3.5cm, which no amount of vertical spacing recovers. Measured: sources alone overflow
    by nothing at all, with every cell at full length and row spacing untouched.

    d1_sources.tex is still written, because the two halves read as one exhibit outside the
    dissertation. Same reasoning as `split_d3`.
    """
    hdr = "% Auto-generated by reports/tables/make_data_tables.py. Do not edit.\n"
    col = r"\newcolumntype{R}[1]{>{\raggedright\arraybackslash}p{#1}}"
    L = body.split("\n")
    i = next(k for k, l in enumerate(L) if l.startswith(r"\multicolumn{6}{@{}l}{\emph{Instrument"))
    assert L[i - 1] == r"\midrule", L[i - 1]

    # L[0] is already the generator header; prepending hdr to it printed the line twice.
    body_lines = L[1:] if L[0].startswith("% Auto-generated") else L[:]
    j = i - 1 - (1 if L[0].startswith("% Auto-generated") else 0)
    sources = hdr + "\n".join(body_lines[:j] + [r"\bottomrule", r"\end{tabular}"]) + "\n"
    instrument = hdr + "\n".join(
        [col, r"\begin{tabular}{@{}R{2.2cm} R{3.0cm} R{3.1cm} R{2.0cm} R{2.0cm} R{1.9cm}@{}}",
         r"\toprule"] + L[i:]) + "\n"
    assert r"\bottomrule" in instrument and "tick size" in instrument
    assert "Book snapshots" in sources and "tick size" not in sources
    # `instrument` above is the LEGACY six-column half, still asserted so the combined
    # d1_sources.tex stays coherent for readers outside the dissertation. The dissertation gets
    # the rebuilt symbol/quantity/value table instead. See table_d1b_instrument's docstring.
    return {"d1a_sources": sources, "d1b_instrument": table_d1b_instrument()}


def split_d3(body: str) -> dict:
    """D3's three panels, one file each.

    The three panels stack to 820pt against 703pt of page height, so they cannot be one
    float; and each belongs beside a different paragraph of section 3.4, so no paragraph
    refers forward. d3_partitions.tex is still written, because the panels read as one
    exhibit outside the dissertation.
    """
    parts = body.split(r"\begin{tabular}")
    panels = [r"\begin{tabular}" + s.split(r"\end{tabular}")[0] + "\\end{tabular}\n"
              for s in parts[1:]]
    assert len(panels) == 3, len(panels)
    hdr = "% Auto-generated by reports/tables/make_data_tables.py. Do not edit.\n"
    return {"d3a_versions": hdr + panels[0],     # section 3.4, paragraph 1
            "d3b_seedsets": hdr + panels[1],     # section 3.4, paragraph 3
            "d3c_december": hdr + panels[2]}     # section 3.4, paragraph 2


def table_d2b() -> str:
    """The per-order record's processing steps, and what was checked at each.

    The parallel to `table_d2`, which does the same for the snapshot record. Three rows only,
    and deliberately so: Table 3.1 already carries the SOURCES (what each stream holds, the
    missing clock, the identifier match, 31 of 31 days, 5,355,301 states) and Table 3.5 carries
    the DIVISION into fitting and holdout hours. Restating either here would be the exhibit-scale
    version of the mistake this chapter has already been caught on twice. What sits nowhere else
    is the processing between them, which is what these three rows hold.
    """
    P = M["perorder_pipeline"]
    rows = [
        (r"warming up the replay",
         (f"the first {n(P['warmup_events'])} changes are applied without being recorded. The replay "
          r"starts from an empty book, and learns of an order only when that order changes, so it "
          r"holds too little volume until the orders present at the start have gone"),
         (f"recording begins {P['grid_start_minutes_into_1_dec']:.1f} minutes into 1 December, leaving hour 0 "
          f"of that day short of book data and outside the regime split, the "
          f"{'only such hour' if P['hours_unlabelled'] == 1 else 'only such hours'} of the month's "
          f"{n(P['hours_expected'])}")),
        (r"removing phantom orders",
         (f"{n(P['phantom_orders_removed'])} orders across the month are removed before they appear. In the "
          r"sub-second ordering of the two streams, a cancellation can be recorded before the order "
          r"it cancels"),
         (r"audited 4 July 2026. One rule, applied uniformly across the month. Without it, such "
          r"orders rest in the book indefinitely")),
        (r"verifying the reconstruction",
         (r"a second, independent pass over the same raw records, advancing the book event by event, "
          r"and sampling it back to the same half-second points"),
         (f"the two methods agree exactly, across all {n(P['n_grid_rows'])} states")),
    ]
    # Columns widened 2026-08-09 to use the full 16cm text width. Table 3.4 sits at the top
    # of the page that also carries ALL of section 3.4's prose; every wrapped line it saves
    # is a line that paragraph needs. See (Y17).
    out = [r"% Auto-generated by reports/tables/make_data_tables.py. Do not edit.",
           r"\begin{tabular}{@{}p{2.4cm} p{7.9cm} p{5.5cm}@{}}", r"\toprule",
           r"step & what it produced & what was checked \\", r"\midrule"]
    out += [" & ".join(c) + r" \\" for c in rows]
    out += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(out) + "\n"


def main() -> None:
    d1, d3 = table_d1(), table_d3()
    outputs = {"d1_sources": d1, "d2_pipeline": table_d2(),
               "d2b_perorder": table_d2b(), "d3_partitions": d3}
    outputs.update(split_d1(d1))
    outputs.update(split_d3(d3))
    for name, body in outputs.items():
        p = HERE / f"{name}.tex"
        p.write_text(body)
        print(f"wrote {p}  ({len(body.splitlines())} lines)")


if __name__ == "__main__":
    main()
