"""Build m6_fidelity.tex -- the calibrated simulator against the real book.

Every number is read from the frozen gate verdicts. NOTHING is typed here.

Source: scratch_hyperliquid/oxford_l4/step3g/gate_verdict_{calm,volatile}_b.json
        (the "_b" bundles are the ones the campaigns ran on)

Run:  .venv/bin/python reports/tables/make_fidelity_table.py
Then: .venv/bin/python reports/tables/sync_to_dissertation.py
"""
from __future__ import annotations

import json
from pathlib import Path

SCRATCH = Path("/Users/fardeenidrus/Desktop/MSc Dissertation/scratch_hyperliquid/oxford_l4")
OUT = Path(__file__).resolve().parent / "m6_fidelity.tex"

# metric key -> reader-facing label. Order is the order of the rows.
LABELS = {
    "M1_vol_1s": "one-second price volatility (ticks)",
    "M2_spread": "spread (ticks)",
    # step3g.py:356 measures state[K]==0 against ask1_zero_uncond: the BEST ASK, not both
    # sides. "inner queue" was undefined in the document and imprecise here.
    "M3_inner_empty": "fraction of time the best ask is empty",
    "M4_limit_share": "share of events that are limit orders",
    "M4_cancel_share": "share of events that are cancellations",
    "M5a_market_btc_per_s_vs_anchor": "market volume per second (BTC)",
}


def load(regime: str) -> dict:
    p = SCRATCH / "step3g" / f"gate_verdict_{regime}_b.json"
    if not p.exists():
        raise SystemExit(f"missing verdict file: {p}")
    return json.loads(p.read_text())


def fmt(x: float) -> str:
    return f"{x:.3f}" if abs(x) < 10 else f"{x:.2f}"


def main() -> None:
    calm, vol = load("calm"), load("volatile")

    hours = {calm["n_calibration_hours"], vol["n_calibration_hours"]}
    seeds = {calm["n_seeds"], vol["n_seeds"]}
    if len(hours) != 1 or len(seeds) != 1:
        raise SystemExit("calm and volatile disagree on hours or seeds; check the verdicts")
    n_hours, n_seeds = hours.pop(), seeds.pop()

    by_regime = {r: {c["metric"]: c for c in d["checks"]} for r, d in (("calm", calm), ("volatile", vol))}

    rows = []
    for key, label in LABELS.items():
        c, v = by_regime["calm"].get(key), by_regime["volatile"].get(key)
        if c is None or v is None:
            raise SystemExit(f"metric {key} missing from a verdict file")
        mark = lambda ch: r"\checkmark" if ch["mean_pass"] else r"$\times$"
        # the band is printed beside the venue value: without it "marginal" is unverifiable
        band = lambda ch: f"{fmt(ch['real'])} ({fmt(ch['band'][0])}--{fmt(ch['band'][1])})"
        rows.append(
            f"{label} & {fmt(c['sim_mean'])} & {band(c)} & {mark(c)} "
            f"& {fmt(v['sim_mean'])} & {band(v)} & {mark(v)} \\\\"
        )

    n_fail = sum(1 for r in ("calm", "volatile") for c in by_regime[r].values() if not c["mean_pass"])

    body = "\n".join(rows)
    tex = f"""% Auto-generated by reports/tables/make_fidelity_table.py from
% step3g/gate_verdict_{{calm,volatile}}_b.json. Do not edit by hand.
\\begin{{tabular}}{{@{{}}p{{0.27\\linewidth}} rr c rr c@{{}}}}
\\toprule
& \\multicolumn{{3}}{{c}}{{calm}} & \\multicolumn{{3}}{{c}}{{volatile}} \\\\
\\cmidrule(lr){{2-4}}\\cmidrule(lr){{5-7}}
measure & simulator & Hyperliquid (band) & & simulator & Hyperliquid (band) & \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
"""
    OUT.write_text(tex)
    print(f"wrote {OUT}")
    print(f"  {n_hours} hours, {n_seeds} seeds, {n_fail} of 12 outside band")
    for r in ("calm", "volatile"):
        for k, c in by_regime[r].items():
            if not c["mean_pass"]:
                print(f"  OUTSIDE BAND  {r:<9} {k:<32} sim {c['sim_mean']:.4f}  venue {c['real']:.4f}")


if __name__ == "__main__":
    main()
