"""Tables D1, D2 and D3 for the Data chapter, built from source. No number is typed here.

Every figure in the three tables is read from a measured artefact at build time:

  data_chapter_measurements.json  coverage states, per-build split boundaries and episode
                                  counts, regime mix, depth by hour
                                  (reports/diagnostics/data_chapter_measure.py)
  phase1_qa.json                  the pipeline stages and their integrity gates
  tick_class_measurement.json     tick, relative tick and the spread distribution
  adv/btc_adv.json                the recorded-book average daily volume and its skew
  trade_volume_202512.json        the per-order month's traded volume
                                  (reports/diagnostics/l4_trade_volume.py)

ONE EXCEPTION, DECLARED. Table D3's Panel B lists the simulator's episode-seed blocks with
their governance status (development, reserve, sealed, spent). A block's STATUS is a human
designation recorded in the partition audit, addendum (Z) of qrm_step5_remediation.md; it is
not derivable from any file, because "sealed and spent" is a statement about how a partition
was licensed and used, not about its contents. Those cells are therefore literals carried
from (Z), marked below, and every numeric cell in the same table is not.

Output: reports/tables/d1_sources.tex, d2_pipeline.tex, d3_partitions.tex
"""
from __future__ import annotations

import json
from pathlib import Path

S = Path("/Users/fardeenidrus/Desktop/MSc Dissertation/scratch_hyperliquid")
HERE = Path(__file__).resolve().parent
REPORTS = HERE.parent

M = json.loads((S / "oxford_l4" / "data_chapter_measurements.json").read_text())
QA = json.loads((REPORTS / "phase1_qa.json").read_text())
TC = json.loads((S / "oxford_l4" / "tick_class" / "tick_class_measurement.json").read_text())
ADV = json.loads((S / "adv" / "btc_adv.json").read_text())
TV = json.loads((S / "oxford_l4" / "trade_volume_202512.json").read_text())["december_only"]

RC = M["raw_coverage"]
B = M["builds"]


def esc(s: str) -> str:
    return s.replace("%", r"\%").replace("&", r"\&").replace("_", r"\_")


def n(x: float, dp: int = 0) -> str:
    """Thousands-separated fixed-point, so a table never invents precision."""
    return f"{x:,.{dp}f}"


# ---------------------------------------------------------------- D1: sources and roles

def table_d1() -> str:
    spread = TC["spread"]["full_month"]
    seven = TC["spread"]["first_7_day_sample"]
    grid_rows_full = 24 * 60 * 60 * 2  # a 0.5-second grid over a full UTC day
    n_l4_days = spread["n_days"]
    prim = 25.0  # the simulator's primary order, BTC

    rows = [
        (r"Book snapshots (Level 2)",
         r"the price and the volume standing at each level, both sides, at the instant the snapshot was taken",
         r"20 price levels each side, averaged into 1-minute and 10-second bars",
         f"{RC['span_start']} to {RC['span_end']} ({RC['span_days']} days)",
         f"{n(RC['n_raw_files'])} separate hourly files",
         r"replaying the historical book"),
        (r"Book changes, order by order (Level 4)",
         r"one change to the visible book, giving the order's identifier, side, price and new size. It has no timestamp",
         f"the book rebuilt at 20 price levels each side, once every half second; 85 columns, so {n(grid_rows_full)} rows in a full day",
         f"December 2025, {n_l4_days} of {n_l4_days} days",
         f"{n(spread['n_samples'])} half-second book snapshots",
         r"fitting the simulator; measuring the venue's order flow"),
        (r"Order events with timestamps (Level 4)",
         r"one record per order event, with a timestamp accurate to the nanosecond and the order's identifier",
         r"not turned into a book; used to timestamp the book changes, matched by order identifier",
         r"December 2025",
         r"---",
         r"supplying the timestamps the book changes lack"),
    ]

    out = [r"% Auto-generated by reports/tables/make_data_tables.py. Do not edit.",
           r"\newcolumntype{R}[1]{>{\raggedright\arraybackslash}p{#1}}",
           r"\begin{tabular}{@{}R{2.2cm} R{3.0cm} R{3.1cm} R{2.0cm} R{2.0cm} R{1.9cm}@{}}",
           r"\toprule",
           r"what was collected & one record holds & processed into & period covered & how much data & used for \\",
           r"\midrule"]
    # Each source row runs to four or five lines, so without separation the three run
    # together. A light rule stays inside booktabs convention; vertical rules do not.
    for i, r in enumerate(rows):
        out.append(" & ".join(esc(c) for c in r) + r" \\")
        if i < len(rows) - 1:
            out.append(r"\addlinespace[2pt]\cmidrule(lr){1-6}\addlinespace[2pt]")
    out += [r"\midrule",
            r"\multicolumn{6}{@{}l}{\emph{Instrument, measured across all "
            + f"{n_l4_days} days and {n(spread['n_samples'])} half-second samples}}" + r"} \\",
            r"\midrule"]

    inst = [
        ("tick size", r"\$1.00, constant across all " + f"{n_l4_days} days"),
        ("median mid", r"\$" + n(spread["median_mid"], 2)),
        ("relative tick", f"{spread['relative_tick']:.3e}"),
        (r"P(spread $=$ 1 tick)", f"{100 * spread['p_spread_1_tick']:.1f}\\% "
                                  f"(first 7-day sample: {100 * seven['p_spread_1_tick']:.1f}\\%)"),
        ("mean spread", f"{spread['mean_spread_ticks']:.3f} ticks, "
                        f"{spread['mean_spread_bps']:.4f} bps"),
    ]
    for k, v in inst:
        out.append(f"\\multicolumn{{2}}{{@{{}}p{{5.5cm}}}}{{{k}}} & "
                   f"\\multicolumn{{4}}{{p{{9.7cm}}@{{}}}}{{{v}}} \\\\")

    out += [r"\midrule",
            r"\multicolumn{6}{@{}l}{\emph{How much the venue trades, and what an order is a "
            r"share of it}} \\",
            r"\midrule"]

    vol = [
        ("average daily volume, two-year span",
         f"{n(ADV['adv_btc'], 2)} BTC a day "
         f"({ADV['window']['start']} to {ADV['window']['end']})"),
        ("median daily volume, same span",
         f"{n(ADV['median_daily_btc'], 0)} BTC, with a range of {n(ADV['min_daily_btc'], 0)} "
         f"to {n(ADV['max_daily_btc'], 0)}"),
        ("average daily volume, December 2025",
         f"{n(TV['mean_daily_btc'], 0)} BTC a day ({TV['date_first']} to {TV['date_last']})"),
        ("order sizes used with the historical snapshots",
         ", ".join(f"{ADV['adv_btc'] * p / 100:.2f} BTC" for p in (0.5, 1.0, 2.0))
         + " (0.5\\%, 1\\% and 2\\% of the two-year daily average)"),
        ("order size used in the simulator",
         f"{prim:g} BTC, which is {100 * prim / TV['mean_daily_btc']:.3f}\\% of an average "
         f"December day"),
    ]
    for k, v in vol:
        out.append(f"\\multicolumn{{2}}{{@{{}}p{{5.5cm}}}}{{{k}}} & "
                   f"\\multicolumn{{4}}{{p{{9.7cm}}@{{}}}}{{{v}}} \\\\")

    out += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(out) + "\n"


# --------------------------------------------------------- D2: pipeline and integrity

def table_d2() -> str:
    s0, s1 = QA["stage0_source_coverage"], QA["stage1_pull"]
    s3, s4 = QA["stage3_minute"], QA["stage4_features"]
    s5, s6 = QA["stage5_regimes"], QA["stage6_datasets"]
    p = s4["params"]
    dropped = s4["feature_valid_rows"] - s6["rows"]

    thr_1min = M["volatility"]["dataset"]["threshold"]
    rows = [
        ("downloading the raw files",
         f"{n(s0['hours_present'])} hourly files, one for each hour obtained. "
         f"{s0['days_fully_covered']} days arrived with all 24 hours, "
         f"{len(s0['days_partial'])} with only some, "
         f"{len(s0['days_missing'])} with none although they were requested, and "
         f"{s0['days_skipped']} were never requested because the venue's archive holds nothing "
         f"for those weeks",
         f"{n(s0['hours_present'])} of the {n(s0['hours_expected'])} hours in the "
         f"{s0['days_in_range_excluding_skips']} days requested, or {s0['coverage_pct']}\\%. "
         f"Measured instead against all {RC['span_days']} days of the two years, including the "
         f"{s0['days_skipped']} never requested, it is {RC['coverage_pct_calendar']}\\%"),
        ("checking the download",
         f"{n(s1['raw_files'])} files on disk against {n(s1['expected'])} expected",
         "every file matched byte for byte" if s1["byte_exact"] else "MISMATCH"),
        ("building one book per minute",
         f"{n(s3['minutes_present'])} minutes, no duplicates, a median of "
         f"{s3['median_snapshots_per_min']:g} snapshots behind each minute",
         "timestamps strictly increasing; bid prices below ask prices at every level"),
        ("computing the input variables",
         f"{n(s4['feature_valid_rows'])} minutes usable of {n(s4['rows'])} ({s4['valid_pct']}\\%). "
         f"Five variables describe each minute: the average gap between the best buy and best "
         f"sell price; the imbalance between the buy and sell volume resting on the best "
         f"{p['imbalance_depth']} levels; the sell-side volume resting on those levels; the "
         f"price change over the previous {p['return_lookback']} minutes; and price volatility "
         f"over the previous {p['vol_window']} minutes",
         "a minute is usable only if all five variables can be computed for it"),
        ("the volatility window, and its cost",
         f"volatility is computed from the previous {p['vol_window']} minutes, and the price "
         f"change from the previous {p['return_lookback']}. If any minute inside either stretch "
         f"is absent, the variable cannot be computed and the minute is discarded rather than "
         f"estimated by interpolation",
         f"no {p['vol_window']}-minute window is ever completed across absent minutes; "
         "\\Cref{fig:d1-coverage} shows where the loss falls"),
        ("cutting the data into episodes",
         f"{n(s4['feature_valid_rows'])} usable minutes became {n(s6['rows'])}. The "
         f"{n(dropped)} difference is minutes left over at the ends, too few to complete an "
         f"episode",
         f"{n(s6['rows'])} $\\div$ {s6['rows'] // s6['episodes']} steps $=$ "
         f"{n(s6['episodes'])} episodes exactly"),
        ("labelling each episode calm or volatile",
         f"the dividing line is {thr_1min:.6f}, the median volatility of the training episodes, "
         f"so half of the training data is labelled volatile by construction",
         f"{n(s5['n_episodes'])} episodes labelled"),
        ("splitting into training and test",
         f"{n(s6['train_rows'])} training rows and {n(s6['test_rows'])} test rows, split by "
         f"date",
         "every training row is dated before every test row"),
        ("guarding against leakage",
         f"every variable is computed from completed minutes only and then shifted by one "
         f"minute, so the values available at any decision point come from minutes strictly "
         f"before it. {s6['nan_in_core_fields']} missing values in the core fields, and the "
         f"scaling constants are computed on the training portion alone and applied unchanged "
         f"elsewhere",
         "no test-period information enters training; the one-minute shift is enforced in code "
         "and unit-tested"),
        ("reproducibility",
         "the pipeline draws no random numbers at any stage",
         "the same input and settings reproduce every file exactly"),
    ]

    out = [r"% Auto-generated by reports/tables/make_data_tables.py. Do not edit.",
           r"\begin{tabular}{@{}p{2.7cm} p{7.2cm} p{5.3cm}@{}}",
           r"\toprule",
           r"step & what it produced & what was checked \\",
           r"\midrule"]
    for a, b, c in rows:
        out.append(f"{esc(a)} & {b} & {c} \\\\")
    out += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(out) + "\n"


# -------------------------------------------------------- D3: partitions and governance

# Panel B literals. Source: qrm_step5_remediation.md addendum (Z), the two-pass partition
# audit. Status is a licensing designation and has no machine-readable source; see the module
# docstring. Numbers inside this panel are counts recorded by that audit.
PANEL_B = [
    ("1e6", "development", "watching training progress. No result was ever judged on it",
     "many", "still available"),
    ("5e6", "development", "the working set: tuning, screening and everyday comparisons",
     "27 campaigns", "still available"),
    ("18e6", "development", "the working set for the environment with the injected signal",
     "4 campaigns", "still available"),
    ("6e6", "reserve", "held back to check whether a development result repeated",
     "1 comparison, 2 settings", "used up"),
    ("19e6", "reserve", "reserve that expired unused, then spent on the pacing-drift test",
     "1", "used up, did not confirm"),
    ("9e6", "confirmation", "first confirmation of the main comparison, one attempt only",
     "1", "used up, no advantage found"),
    ("13e6", "confirmation", "second confirmation of the main comparison, one attempt only",
     "1", "used up, no advantage found"),
    ("25e6", "confirmation", "created for the amended observation specification",
     "1 pre-registration, 2 arms", "used up, no advantage found"),
    ("17e6", "confirmation", "created for the injected-signal extension, one attempt only",
     "1", "used up"),
    ("21e6", "confirmation", "created to confirm the best attainable improvement, one attempt",
     "1", "used up"),
    ("3e6", "environment check", "certifying the simulator itself, never used to judge a method",
     "---", "not a comparison set"),
    ("30e6, 31e6, 77M", "measurement", "diagnostic measurements only",
     "---", "no result was ever judged on them"),
]

BUILD_ORDER = [("dataset_10s", r"\textbf{10-second (main)}"),
               ("dataset", "1-minute"),
               ("dataset_10s_10min", "10-second, shorter episode")]


def table_d3() -> str:
    out = [r"% Auto-generated by reports/tables/make_data_tables.py. Do not edit.",
           r"\begin{tabular}{@{}l l r r r l r@{}}",
           r"\multicolumn{7}{@{}l}{\textbf{Panel A. Historical data: split by date, three "
           r"versions of the dataset}} \\",
           r"\toprule",
           r"version & bar width, steps, episode & training & tuning & held-out test & "
           r"last training bar $\rightarrow$ first test bar & test: calm / volatile \\",
           r"\midrule"]
    for key, label in BUILD_ORDER:
        b = B[key]
        steps = b["steps_per_episode"]
        bar = {"dataset": "1\\,min", "dataset_10s": "10\\,s", "dataset_10s_10min": "10\\,s"}[key]
        horizon = {"dataset": "30\\,min", "dataset_10s": "30\\,min",
                   "dataset_10s_10min": "10\\,min"}[key]
        last = b["train_last_ts"][:19].replace(" ", "\\,")
        first = b["test_first_ts"][:19].replace(" ", "\\,")
        out.append(
            f"{label} & {bar}, {steps}, {horizon} & {n(b['episodes_train_only'])} & "
            f"{n(b['episodes_validation'])} & {n(b['episodes_test'])} & "
            f"\\scriptsize {last} $\\rightarrow$ {first} & "
            f"{n(b['test_regime']['calm'])}/{n(b['test_regime']['volatile'])} \\\\")
    out += [r"\midrule",
            r"\multicolumn{7}{@{}p{15.2cm}}{\footnotesize The three versions do not share a "
            r"boundary. The split falls at the same fraction of each version's own row count, "
            r"and the versions contain different numbers of rows, so that fraction lands on a "
            r"different date in each. Tuning episodes are the last 15\% of the training file by "
            r"date. In all three, every training bar is dated before every test bar.} \\",
            r"\bottomrule",
            r"\end{tabular}",
            r"",
            r"\vspace{0.6em}",
            r"",
            r"\begin{tabular}{@{}l l p{6.0cm} l l@{}}",
            r"\multicolumn{5}{@{}l}{\textbf{Panel B. Simulated data: sets of episodes drawn "
            r"from separate random seeds, not dates}} \\",
            r"\toprule",
            r"seed set & kind & what it was for & times used & standing now \\",
            r"\midrule"]
    for blk, kind, role, uses, status in PANEL_B:
        out.append(f"{esc(blk)} & {esc(kind)} & {esc(role)} & {esc(uses)} & {esc(status)} \\\\")
    out += [r"\midrule",
            r"\multicolumn{5}{@{}p{15.2cm}}{\footnotesize A confirmation set is opened once, "
            r"scored once, and never reused, so that a result cannot be improved by retrying. "
            r"None of the five confirmation sets appears in more than one result.} \\",
            r"\bottomrule",
            r"\end{tabular}"]
    return "\n".join(out) + "\n"


def main() -> None:
    for name, body in (("d1_sources", table_d1()),
                       ("d2_pipeline", table_d2()),
                       ("d3_partitions", table_d3())):
        p = HERE / f"{name}.tex"
        p.write_text(body)
        print(f"wrote {p}  ({len(body.splitlines())} lines)")


if __name__ == "__main__":
    main()
